### ISSUE TITLE
remove NRI related data from repo

### ISSUE THREAD

**Issue by michaelglass** [NoRedInk/live_fixtures#2]
remove NRI related data from repo via rewriting history before making this repo public

**Comment by raorao** [comment]
what nri data?

**Comment by michaelglass** [comment]
all of the fake data from teacher user in the test dir implicitly has our schema, which significantly increases the ability to fuck with us via sql injection.

**Comment by raorao** [comment]
:heart:. Should be easy to fix.

**Comment by ento** [comment]
force-pushed a cleaned repo
