### ISSUE TITLE
optionally supress console output

### ISSUE THREAD

**Issue by raorao** [NoRedInk/live_fixtures#3]
helpful for running in remote environments.

**Comment by SamGerber-zz** [comment]
Note the progress bar automatically detects if it's writing to a non tty output: 
https://github.com/jfelchner/ruby-progressbar/wiki/Non-TTY-Output

There are a few ways we could go about this:
 1. Pass StringIO as the output option when we initialize the ProgressBar.
 2. Change the format from a progress bar to just printing the title. I'm not convinced this is optimized to prevent clearing and reprinting every time we call increment.
3. Optionally use a simple iterator in place of the ProgressBarIterator.
